'use client';
import { useState } from 'react';
import { useApi } from '@/lib/useApi';
import { api } from '@/lib/api';
import { money } from '@/lib/format';
import { Card, Stat, Badge, SectionTitle, Table, Loading, ErrorNote } from '@/components/ui';

interface Summary {
  ledger: Record<string, number>;
  owedCents: number;
  paidCents: number;
  payableCents: number;
  conversions: number;
  flaggedConversions: number;
  partners: number;
  offers: number;
  events: number;
}
interface PartnerRow {
  id: string;
  name: string;
  status: string;
  owed_cents: string;
  paid_cents: string;
  conversions: string;
}
interface Insights {
  generatedBy: string;
  headline: string[];
  narrative: string | null;
}

const LEDGER_ORDER = ['pending', 'confirmed', 'payable', 'paid', 'reversed', 'clawed_back'];

export default function Dashboard() {
  const summary = useApi<Summary>('/reports/summary');
  const partners = useApi<PartnerRow[]>('/reports/partners');
  const [insights, setInsights] = useState<Insights | null>(null);
  const [loadingInsights, setLoadingInsights] = useState(false);

  async function runInsights() {
    setLoadingInsights(true);
    try {
      setInsights(await api.get<Insights>('/insights/partners'));
    } finally {
      setLoadingInsights(false);
    }
  }

  if (summary.error) return <ErrorNote message={summary.error} />;
  if (!summary.data) return <Loading label="Loading dashboard" />;
  const s = summary.data;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-slate-100">Program overview</h1>
        <p className="text-sm text-slate-500">Live attribution and settlement across your partner program.</p>
      </div>

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <Stat label="Outstanding liability" value={money(s.owedCents)} sub="pending + confirmed + payable" />
        <Stat label="Ready to pay" value={money(s.payableCents)} accent sub="payable now" />
        <Stat label="Paid to date" value={money(s.paidCents)} />
        <Stat label="Conversions" value={s.conversions} sub={`${s.events} tracked events`} />
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <Card className="lg:col-span-1">
          <SectionTitle title="Ledger by state" />
          <div className="space-y-2">
            {LEDGER_ORDER.map((state) => (
              <div key={state} className="flex items-center justify-between">
                <Badge kind={state}>{state.replace('_', ' ')}</Badge>
                <span className="text-sm tabular-nums text-slate-300">{money(s.ledger[state] ?? 0)}</span>
              </div>
            ))}
          </div>
          <div className="mt-4 border-t border-ink-800 pt-3 text-sm">
            <div className="flex justify-between text-slate-400">
              <span>Flagged for review</span>
              <span className="text-rose-300">{s.flaggedConversions}</span>
            </div>
          </div>
        </Card>

        <Card className="lg:col-span-2">
          <SectionTitle
            title="AI partner insights"
            action={
              <button onClick={runInsights} className="btn-ghost py-1.5" disabled={loadingInsights}>
                {loadingInsights ? 'Analyzing…' : 'Generate'}
              </button>
            }
          />
          {!insights && <p className="text-sm text-slate-500">Generate insights to surface activation gaps and payout risk.</p>}
          {insights && (
            <div className="space-y-3">
              <ul className="space-y-1.5 text-sm text-slate-300">
                {insights.headline.map((h, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="text-brand-400">›</span>
                    {h}
                  </li>
                ))}
              </ul>
              {insights.narrative && (
                <p className="rounded-lg border border-ink-700 bg-ink-900/60 p-3 text-sm text-slate-400">{insights.narrative}</p>
              )}
              <p className="text-xs text-slate-600">Generated by: {insights.generatedBy}</p>
            </div>
          )}
        </Card>
      </div>

      <div>
        <SectionTitle title="Partner leaderboard" />
        {partners.loading && <Loading />}
        {partners.data && (
          <Table head={['Partner', 'Status', 'Conversions', 'Owed', 'Paid']}>
            {partners.data.map((p) => (
              <tr key={p.id}>
                <td className="td font-medium text-slate-100">{p.name}</td>
                <td className="td">
                  <Badge>{p.status}</Badge>
                </td>
                <td className="td tabular-nums">{p.conversions}</td>
                <td className="td tabular-nums">{money(p.owed_cents)}</td>
                <td className="td tabular-nums text-brand-400">{money(p.paid_cents)}</td>
              </tr>
            ))}
          </Table>
        )}
      </div>
    </div>
  );
}
